DEEPSORT:
  REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100

USE_MMDET: False
USE_FASTREID: False

USE_AICITYREID: True
AICITYREID:
  INPUT:
    SIZE_TEST: [384, 384]
  INPUTSIZE: 320
  MODEL_PATH: "checkpoints/net_last.pth"
  CONFIG_PATH: "configs/opts.yaml"
  CFG: "configs/deep_sort.yaml"

YOLOX:
  EXP_NAME: 'yolox-x'
  CKPT_FILE: '/dataset/mz/code/yoloxServer-vehicle/weights/yolox_x.pth'
